### PR TITLE
SVG animation

### PR DESCRIPTION
**Pull request by rhaps0dy**
From #739

The animation isn't quite smooth and it generates huge files (the board is copied to each frame) but it works!

TODO
- [ ] Make sure animation is smooth 

Chess animation

@sotetsuk Do you like the API?

### CODE REVIEW

**Comment by rhaps0dy** [comment]
Possible other changes:
* add API function that returns an SVG as string, which will be good for displaying these in Jupyter notebooks / uploading to Weights & Biases
* Reduce file size 

Do I have to do them to get merged? I'd rather have someone else work on reducing the file size.

**Comment by sotetsuk** [comment]
Amazing! 😍 It's really interesting that such a small change can generate animation 😳 

This PR looks perfect! I'll merge it without any changes.

> Do you like the API?

I like it 👍 It's simple and explicit. I believe it's user-friendly 👍 

> Do I have to do them to get merged? I'd rather have someone else work on reducing the file size.

I think this PR is ready to merge. We prefer smaller PRs than one big PR.
You may be able to send another PR!

Possible other changes also look super cool 🤘 PRs are more than welcome 👍

**Review by sotetsuk — APPROVED** [review]
@rhaps0dy If you are OK, I'll merge this PR!

**Comment by sotetsuk** [comment]
PS: I personally think it's very smooth 😄

**Comment by rhaps0dy** [comment]
Thank you! Yeah, I think there's problems (on the web browser end) with rendering it when the file size is large. For the size I posted (50 frames) it's not a problem, but I think the full randomly-generated chess game does have problems.

I'm happy to merge this if you're happy with it!

**Comment by rhaps0dy** [comment]
Note that I haven't tested this with anything other than chess and Go and tictactoe.

**Pull request merged**
